//! AUTOLAB OT-2 protocol compiler. Offline; no live robot in CI.
//!
//! Ports `_ot2_normalize_plan` + `_ot2_compile_protocol`. Physical motion
//! always requires an explicit confirm flag.

use std::collections::{BTreeMap, BTreeSet};

use serde_json::{Value, json};

/// Default Protocol API level.
pub const OT2_DEFAULT_API_LEVEL: &str = "2.13";
/// Deck slots that may hold labware (trash is 12).
pub const OT2_SLOTS: &[u8] = &[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11];

/// Compiler / gate errors.
#[derive(Clone, Debug, thiserror::Error, PartialEq, Eq)]
pub enum AutolabError {
    /// Plan failed validation.
    #[error("invalid plan: {0}")]
    Invalid(String),
    /// Motion was requested without confirm.
    #[error("refusing ungated robot motion — pass confirm=true after a human check")]
    MotionNotConfirmed,
}

/// One labware load.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Ot2Labware {
    /// Canonical or alias load name.
    pub labware: String,
    /// Deck slot 1–11.
    pub slot: u8,
}

/// One legacy transfer.
#[derive(Clone, Debug, PartialEq)]
pub struct Ot2Transfer {
    /// `labwareId:well`
    pub from: String,
    /// `labwareId:well`
    pub to: String,
    /// Microlitres.
    pub volume: f64,
}

/// Transfer plan (fixture-friendly).
#[derive(Clone, Debug, PartialEq)]
pub struct Ot2Plan {
    /// Protocol name.
    pub name: String,
    /// Author.
    pub author: String,
    /// Description.
    pub description: String,
    /// Pipette load name.
    pub pipette: String,
    /// `left` or `right`.
    pub mount: String,
    /// Tip racks.
    pub tips: Vec<Ot2Labware>,
    /// Labware by id.
    pub labware: BTreeMap<String, Ot2Labware>,
    /// Legacy transfer list.
    pub transfers: Vec<Ot2Transfer>,
    /// `always` / `once` / `never`.
    pub new_tip: String,
    /// Protocol API level.
    pub api_level: String,
}

/// Compiler output.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Ot2Compile {
    /// Opentrons Protocol API v2 Python text.
    pub protocol_text: String,
    /// Normalised plan as JSON (no live robot).
    pub json: Value,
}

/// Friendly aliases → Opentrons load names.
#[must_use]
pub fn resolve_labware(name: &str) -> String {
    match name {
        "tiprack_300" => "opentrons_96_tiprack_300ul",
        "tiprack_20" => "opentrons_96_tiprack_20ul",
        "tiprack_1000" => "opentrons_96_tiprack_1000ul",
        "eppi_24" | "tuberack_24" => "opentrons_24_tuberack_eppendorf_1.5ml_safelock_snapcap",
        "plate_24" => "corning_24_wellplate_3.4ml_flat",
        "plate_96" => "nest_96_wellplate_100ul_pcr_full_skirt",
        other => other,
    }
    .to_owned()
}

/// Built-in fixture used by tests and the AUTOLAB overlay.
#[must_use]
pub fn fixture_deck() -> Ot2Plan {
    let mut labware = BTreeMap::new();
    labware.insert(
        "src".into(),
        Ot2Labware {
            labware: "eppi_24".into(),
            slot: 1,
        },
    );
    labware.insert(
        "dst".into(),
        Ot2Labware {
            labware: "plate_24".into(),
            slot: 2,
        },
    );
    Ot2Plan {
        name: "fixture transfer".into(),
        author: "SpliceCraft.rs".into(),
        description: "Generated by SpliceCraft from a fixture deck.".into(),
        pipette: "p300_single".into(),
        mount: "left".into(),
        tips: vec![Ot2Labware {
            labware: "tiprack_300".into(),
            slot: 8,
        }],
        labware,
        transfers: vec![Ot2Transfer {
            from: "src:A1".into(),
            to: "dst:A1".into(),
            volume: 50.0,
        }],
        new_tip: "always".into(),
        api_level: OT2_DEFAULT_API_LEVEL.into(),
    }
}

/// Compile a plan into protocol text + JSON. No network.
pub fn compile_protocol(plan: &Ot2Plan) -> Result<Ot2Compile, AutolabError> {
    let errors = validate_plan(plan);
    if !errors.is_empty() {
        return Err(AutolabError::Invalid(errors.join("; ")));
    }
    let protocol_text = emit_protocol(plan);
    let json = plan_json(plan);
    Ok(Ot2Compile {
        protocol_text,
        json,
    })
}

/// Physical run gate. CI never calls this with a live host.
pub fn confirm_motion(confirm: bool) -> Result<(), AutolabError> {
    if confirm {
        Ok(())
    } else {
        Err(AutolabError::MotionNotConfirmed)
    }
}

fn validate_plan(plan: &Ot2Plan) -> Vec<String> {
    let mut errors = Vec::new();
    if !KNOWN_PIPETTES.contains(&plan.pipette.as_str()) {
        errors.push(format!("unknown pipette {}", plan.pipette));
    }
    if plan.mount != "left" && plan.mount != "right" {
        errors.push(format!("mount must be left or right, not {}", plan.mount));
    }
    if plan.transfers.is_empty() {
        errors.push("no transfers: add at least one entry to 'transfers'".into());
    }
    let mut slots = BTreeSet::new();
    for t in &plan.tips {
        slot_ok(t.slot, &mut slots, &mut errors);
    }
    for (id, lw) in &plan.labware {
        if id.is_empty() {
            errors.push("empty labware id".into());
        }
        slot_ok(lw.slot, &mut slots, &mut errors);
    }
    for (i, t) in plan.transfers.iter().enumerate() {
        let tag = format!("transfer #{}", i + 1);
        if split_ref(&t.from).is_none() {
            errors.push(format!("{tag} from is not labwareId:well"));
        } else if let Some((lid, _)) = split_ref(&t.from)
            && !plan.labware.contains_key(lid)
        {
            errors.push(format!("{tag} unknown source {lid}"));
        }
        if split_ref(&t.to).is_none() {
            errors.push(format!("{tag} to is not labwareId:well"));
        } else if let Some((lid, _)) = split_ref(&t.to)
            && !plan.labware.contains_key(lid)
        {
            errors.push(format!("{tag} unknown dest {lid}"));
        }
        if !t.volume.is_finite() || t.volume <= 0.0 {
            errors.push(format!("{tag} volume must be a positive number"));
        }
    }
    errors
}

fn slot_ok(slot: u8, used: &mut BTreeSet<u8>, errors: &mut Vec<String>) {
    if !OT2_SLOTS.contains(&slot) {
        errors.push(format!("slot {slot} is not a labware slot (1–11)"));
        return;
    }
    if !used.insert(slot) {
        errors.push(format!("slot {slot} is used twice"));
    }
}

fn split_ref(ref_: &str) -> Option<(&str, &str)> {
    let (lid, well) = ref_.split_once(':')?;
    let lid = lid.trim();
    let well = well.trim();
    if lid.is_empty() || well.is_empty() {
        None
    } else {
        Some((lid, well))
    }
}

fn safe_var(label: &str, prefix: &str) -> String {
    let cleaned: String = label
        .chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || ch == '_' {
                ch
            } else {
                '_'
            }
        })
        .collect();
    let cleaned = if cleaned.is_empty() {
        "x".into()
    } else {
        cleaned
    };
    format!("{prefix}{cleaned}")
}

fn py_str(s: &str) -> String {
    serde_json::to_string(s).unwrap_or_else(|_| "\"\"".into())
}

fn emit_protocol(plan: &Ot2Plan) -> String {
    let mut out = vec![
        "from opentrons import protocol_api".into(),
        String::new(),
        "metadata = {".into(),
        format!("    \"protocolName\": {},", py_str(&plan.name)),
        format!("    \"author\": {},", py_str(&plan.author)),
        format!("    \"description\": {},", py_str(&plan.description)),
        format!("    \"apiLevel\": {},", py_str(&plan.api_level)),
        "}".into(),
        String::new(),
        "# Generated by SpliceCraft.rs. ALWAYS re-check with the robot's analysis".into(),
        "# before running on hardware.".into(),
        String::new(),
        "def run(protocol: protocol_api.ProtocolContext):".into(),
    ];

    let mut tip_vars = Vec::new();
    for t in &plan.tips {
        let var = safe_var(&t.slot.to_string(), "tips_");
        tip_vars.push(var.clone());
        out.push(format!(
            "    {var} = protocol.load_labware({}, {})",
            py_str(&resolve_labware(&t.labware)),
            t.slot
        ));
    }

    let mut id_var = BTreeMap::new();
    let mut used: BTreeSet<String> = tip_vars.iter().cloned().collect();
    for (lid, lw) in &plan.labware {
        let mut var = safe_var(lid, "lw_");
        if used.contains(&var) {
            let mut k = 2u32;
            while used.contains(&format!("{var}_{k}")) {
                k += 1;
            }
            var = format!("{var}_{k}");
        }
        used.insert(var.clone());
        id_var.insert(lid.clone(), var.clone());
        out.push(format!(
            "    {var} = protocol.load_labware({}, {})",
            py_str(&resolve_labware(&lw.labware)),
            lw.slot
        ));
    }

    out.push(format!(
        "    pipette = protocol.load_instrument({}, {}, tip_racks=[{}])",
        py_str(&plan.pipette),
        py_str(&plan.mount),
        tip_vars.join(", ")
    ));
    out.push("    protocol.home()".into());

    let volumes: Vec<String> = plan
        .transfers
        .iter()
        .map(|t| format!("{}", t.volume))
        .collect();
    let srcs: Vec<String> = plan
        .transfers
        .iter()
        .map(|t| {
            let (lid, well) = split_ref(&t.from).expect("validated");
            format!("{}[{}]", id_var[lid], py_str(well))
        })
        .collect();
    let dsts: Vec<String> = plan
        .transfers
        .iter()
        .map(|t| {
            let (lid, well) = split_ref(&t.to).expect("validated");
            format!("{}[{}]", id_var[lid], py_str(well))
        })
        .collect();
    out.push("    pipette.transfer(".into());
    out.push(format!("        [{}],", volumes.join(", ")));
    out.push(format!("        [{}],", srcs.join(", ")));
    out.push(format!("        [{}],", dsts.join(", ")));
    out.push(format!("        new_tip={},", py_str(&plan.new_tip)));
    out.push("    )".into());
    out.push(String::new());
    out.join("\n")
}

fn plan_json(plan: &Ot2Plan) -> Value {
    json!({
        "name": plan.name,
        "author": plan.author,
        "description": plan.description,
        "pipette": plan.pipette,
        "mount": plan.mount,
        "api_level": plan.api_level,
        "new_tip": plan.new_tip,
        "tips": plan.tips.iter().map(|t| json!({
            "labware": resolve_labware(&t.labware),
            "slot": t.slot,
        })).collect::<Vec<_>>(),
        "labware": plan.labware.iter().map(|(id, lw)| (id.clone(), json!({
            "labware": resolve_labware(&lw.labware),
            "slot": lw.slot,
        }))).collect::<BTreeMap<_, _>>(),
        "transfers": plan.transfers.iter().map(|t| json!({
            "from": t.from,
            "to": t.to,
            "volume": t.volume,
        })).collect::<Vec<_>>(),
    })
}

const KNOWN_PIPETTES: &[&str] = &[
    "p10_single",
    "p50_single",
    "p300_single",
    "p1000_single",
    "p20_single_gen2",
    "p300_single_gen2",
    "p1000_single_gen2",
    "p20_multi_gen2",
    "p300_multi_gen2",
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fixture_deck_compiles_protocol_and_json() {
        let compiled = compile_protocol(&fixture_deck()).unwrap();
        assert!(
            compiled
                .protocol_text
                .contains("from opentrons import protocol_api"),
            "{}",
            compiled.protocol_text
        );
        assert!(compiled.protocol_text.contains("def run("));
        assert!(compiled.protocol_text.contains("pipette.transfer("));
        assert!(compiled.protocol_text.contains("fixture transfer"));
        assert_eq!(compiled.json["pipette"], "p300_single");
        assert_eq!(compiled.json["transfers"][0]["volume"], 50.0);
        assert_eq!(
            compiled.json["labware"]["src"]["labware"],
            "opentrons_24_tuberack_eppendorf_1.5ml_safelock_snapcap"
        );
    }

    #[test]
    fn invalid_plan_is_refused() {
        let mut p = fixture_deck();
        p.transfers.clear();
        let err = compile_protocol(&p).unwrap_err();
        assert!(matches!(err, AutolabError::Invalid(_)));
    }

    #[test]
    fn motion_requires_confirm() {
        assert!(confirm_motion(false).is_err());
        assert!(confirm_motion(true).is_ok());
    }
}
